# Generated by Django 4.1.6 on 2023-02-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
